version: '3.8'

services:
  tf_serving:
    image: emacski/tensorflow-serving:latest-linux_arm64
    container_name: tf_serving_container
    ports:
      - "8501:8501"
    volumes:
      - ./fastapi/models:/models
    command: "--model_config_file=/models/models.config"
  
  fastapi:
    build:
      context: ./devops/docker/python
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - tf_serving
    volumes:
      - ./fastapi:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: ../devops/docker/node/Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app
    command: npm start
  
  
