--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tb_models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_models (
    id bigint NOT NULL,
    model_name character varying(255)
);


ALTER TABLE public.tb_models OWNER TO postgres;

--
-- Name: tb_models_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_predictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_predictions (
    id bigint NOT NULL,
    result character varying(255),
    model_id bigint,
    user_id bigint
);


ALTER TABLE public.tb_predictions OWNER TO postgres;

--
-- Name: tb_predictions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_predictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_predictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_users (
    id bigint NOT NULL,
    username character varying(255),
    userpassword character varying(255)
);


ALTER TABLE public.tb_users OWNER TO postgres;

--
-- Name: tb_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tb_models; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_models (id, model_name) FROM stdin;
1	cifar10
2	iris
\.


--
-- Data for Name: tb_predictions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_predictions (id, result, model_id, user_id) FROM stdin;
1	automobile	1	2
\.


--
-- Data for Name: tb_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_users (id, username, userpassword) FROM stdin;
1	11	$2a$10$WhuYIFAEAyOyujt8RiIgkui2UlvjkOJybeLCt0z.5/ZQf0gpS6qlO
2	1	$2a$10$grhoc9KR4u/vVFs4GSIy5eNr5AmnnExbEHqUQhOR9TcRYhlQMtv/e
\.


--
-- Name: tb_models_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_models_id_seq', 1, false);


--
-- Name: tb_predictions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_predictions_id_seq', 1, true);


--
-- Name: tb_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_users_id_seq', 2, true);


--
-- Name: tb_models tb_models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_models
    ADD CONSTRAINT tb_models_pkey PRIMARY KEY (id);


--
-- Name: tb_predictions tb_predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_predictions
    ADD CONSTRAINT tb_predictions_pkey PRIMARY KEY (id);


--
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (id);


--
-- Name: tb_predictions fk45r3bxyaqshvq581r50xpy1y9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_predictions
    ADD CONSTRAINT fk45r3bxyaqshvq581r50xpy1y9 FOREIGN KEY (user_id) REFERENCES public.tb_users(id) ON DELETE CASCADE;


--
-- Name: tb_predictions fkeckoixgeb9mhhqdar9u298i7o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_predictions
    ADD CONSTRAINT fkeckoixgeb9mhhqdar9u298i7o FOREIGN KEY (model_id) REFERENCES public.tb_models(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

